extension Strings {
    /// The settings window's tabs, Creatures, Talk, Voice, Costs and Chats.
    static let ruSettingsA: [String: String] = [
        // Tabs
        "Creatures": "Существа",
        "Sprites": "Спрайты",
        "Talk": "Разговоры",
        "Flowers": "Цветы",
        "Bonds": "Отношения",
        "Calendar": "Календарь",
        "Reminders": "Напоминания",
        "Voice": "Голос",
        "Costs": "Расходы",
        "Chats": "Чаты",

        // Shared bits
        " min": " мин",
        " s": " с",
        "never": "никогда",
        "on": "вкл.",
        "off": "выкл.",
        "Status": "Состояние",
        "not checked": "не проверено",
        "checking…": "проверка…",
        "Check": "Проверить",
        "Reset": "Сбросить",
        "Server": "Сервер",
        "Model": "Модель",
        "API key": "Ключ API",
        "Characters": "Персонажи",
        "Reveal in Finder": "Показать в Finder",
        "line|lines": "реплика|реплики|реплик",
        "token|tokens": "токен|токена|токенов",
        "voice|voices": "голос|голоса|голосов",
        "call|calls": "вызов|вызова|вызовов",

        // Creatures
        "How many": "Сколько",
        "Smallest": "Самый маленький",
        "Largest": "Самый большой",
        "Every creature gets its own size between the two. Set them equal and they all match.": "Каждое существо получает свой размер между этими двумя. Сделайте их равными — и все будут одного размера.",
        "Colour %d": "Цвет %d",
        "Add Colour": "Добавить цвет",
        "Remove Last": "Убрать последний",
        "Colours": "Цвета",
        "Creature 1 wears the first colour, creature 2 the second, and so on, starting over when the colours run out.": "Существо 1 носит первый цвет, существо 2 — второй и так далее; когда цвета кончаются, всё начинается сначала.",
        "Sit down to tea now and then": "Иногда садиться пить чай",
        "Share of bumps": "Доля встреч",
        "Lasts": "Длится",
        "Sip between stories": "Глоток между историями",
        "Tea parties": "Чаепития",
        "Now and then two creatures who bump into each other put a little table out between them and sit down to tea, taking turns to tell each other stories from their lives. One party at a time. With talk off they just sip.": "Иногда два столкнувшихся существа ставят между собой столик и садятся пить чай, по очереди рассказывая друг другу истории из жизни. Одно чаепитие за раз. Если разговоры выключены, они просто пьют чай.",
        "Day lasts": "День длится",
        "Night lasts": "Ночь длится",
        "Day and night": "День и ночь",
        "They walk by day and sleep by night. Set the night to 0 and they never sleep. A cursor still startles a sleeper awake.": "Днём они гуляют, ночью спят. Поставьте ночь на 0 — и они не будут спать вовсе. Курсор всё равно спугнёт спящего.",
        "Complain when pushed around": "Жаловаться, когда их гоняют",
        "Puts up with": "Терпит",
        "%d in a row": "подряд: %d",
        "Calms down after": "Успокаивается через",
        "Patience": "Терпение",
        "Chase a creature with the cursor or pick it up more than this many times in a row, and it tells you off in its own voice. Leave it alone this long and it starts counting again.": "Погоняйтесь за существом курсором или поднимите его больше этого числа раз подряд — и оно отчитает вас своим голосом. Оставьте его в покое на это время, и счёт начнётся заново.",
        "Keep the sheet up after an action": "Не закрывать лист после действия",
        "Creature Actions": "Действия существ",
        "On, the Creature Actions sheet stays up until you press Done; off, it folds away after one action.": "Если включено, лист «Действия существ» остаётся открытым, пока вы не нажмёте «Готово»; если выключено — закрывается после одного действия.",
        "Actions": "Действия",
        "When the icon is hidden": "Когда значок спрятан",
        "macOS hides menu bar icons it has no room for. The shortcut reaches the creatures anyway, whichever app is in front. It opens the Creature Actions sheet, and pressed again puts it away; or the whole menu under the cursor, with Settings and Quit. Click the shortcut to record another: a key with Command, Control or Option held. Esc keeps the old one.": "macOS прячет значки, которым не хватило места в строке меню. Сочетание клавиш всё равно дотянется до существ, какая бы программа ни была впереди. Оно открывает лист «Действия существ», а повторное нажатие его убирает; или всё меню под курсором, с настройками и выходом. Нажмите на сочетание, чтобы записать другое: клавишу вместе с Command, Control или Option. Esc оставит прежнее.",
        "Shortcut from any app": "Сочетание клавиш из любой программы",
        "Shortcut": "Сочетание клавиш",
        "It opens": "Оно открывает",
        "The whole menu": "Всё меню",
        "Press the keys…": "Нажмите клавиши…",
        "key %d": "клавиша %d",
        "macOS would not take %@: another app holds it. Record another.": "macOS не приняла %@: это сочетание занято другой программой. Запишите другое.",
        "Start Ledgelings when you log in": "Запускать Ledgelings при входе в систему",
        "Language and startup": "Язык и запуск",
        "Menus, settings and what the creatures say. Prompts you edited stay as written. Login uses the system's Login Items.": "Меню, настройки и речь существ. Изменённые вами промпты не меняются. Запуск — через системные объекты входа.",

        // Talk
        "Creatures talk when they bump into each other": "Существа разговаривают при встрече",
        "Bubble stays": "Реплика видна",
        "Not repeating their last": "Не повторяют последние",
        "Paper planes": "Бумажные самолётики",
        "A paper plane every": "Самолётик каждые",
        "Two creatures meeting on the same edge trade a line and a reply. Every third meeting of a pair, one gives the other a flower (the Flowers tab). Every so often one folds a note into a paper plane and throws it to another; its own wind swirls it across the screen, the catcher reads it out, thinks aloud about it and throws one answer back. \"Make Someone Talk\" and \"Send a Paper Plane\" in the menu work at any time. Longer lines stay up a little longer; a click on a bubble closes it. Each creature remembers its last lines and says something else until it has run through the rest; a model is shown them and asked for something new.": "Два существа, встретившись на одном краю, обмениваются репликой и ответом. На каждой третьей встрече пары одно дарит другому цветок (вкладка «Цветы»). Время от времени кто-нибудь складывает записку в бумажный самолётик и бросает другому; собственный ветер кружит его по экрану, поймавший читает записку вслух, размышляет о ней и бросает ответ. Заставить кого-нибудь заговорить или отправить самолётик можно в любой момент из меню. Длинные реплики висят чуть дольше; щелчок по пузырю закрывает его. Каждое существо помнит свои последние реплики и говорит что-то другое, пока не переберёт остальные; модели их показывают и просят что-то новое.",
        "Brain": "Мозг",
        "Room for each line": "Место на реплику",
        "Species": "Вид",
        "Name": "Имя",
        "Who they are": "Кто это",
        "Add Character": "Добавить персонажа",
        "Reset Cast": "Сбросить состав",
        "Every species has its own cast. The first creature wearing a species is its first character, the second its second, and so on, starting over when the cast runs out. The species itself is described to the model, so a frog talks like a frog.": "У каждого вида свой состав. Первое существо этого вида — его первый персонаж, второе — второй и так далее; когда состав кончается, всё начинается сначала. Сам вид тоже описывается модели, так что лягушка говорит как лягушка.",
        "Who is speaking (system prompt)": "Кто говорит (системный промпт)",
        "Opening line": "Первая реплика",
        "Reply": "Ответ",
        "Reset Prompts": "Сбросить промпты",
        "Prompts": "Промпты",
        "Placeholders: %@. {situation} is written by the app: your time, date and holidays (Calendar tab), the colony's day or night, and where each creature is. {line} is what was just said, for the reply. {relationship} is how the two get on and the story between them (Bonds tab); left out, it goes at the end of the prompt.": "Подстановки: %@. {situation} пишет само приложение: ваше время, дата и праздники (вкладка «Календарь»), день или ночь в колонии и где находится каждое существо. {line} — только что сказанное, для ответа. {relationship} — как эти двое ладят и их общая история (вкладка «Отношения»); если её нет в промпте, она добавляется в конец.",
        "No model, no server, no key: the creatures say these lines. The format is explained at the top of the text. \"Copy Agent Prompt\" puts a request on the clipboard that any chat model answers with more blocks in this format, ready to paste here.": "Без модели, сервера и ключа: существа говорят эти реплики. Формат объяснён в начале текста. «Скопировать промпт для агента» кладёт в буфер обмена запрос, на который любая чат-модель ответит новыми блоками в этом формате — их можно сразу вставить сюда.",
        "LM Studio's local server, started with `lms server start` or from its Developer tab. The model must be one it has installed; \"Check\" lists them. \"Room for each line\": tokens per line, thinking included; too few and a thinking model stops mid-sentence.": "Локальный сервер LM Studio, запускается командой `lms server start` или на его вкладке Developer. Модель должна быть установлена в LM Studio; «Проверить» покажет список. «Место на реплику» — токенов на реплику вместе с размышлениями; если их мало, думающая модель обрывается на полуслове.",
        "OpenRouter runs on the internet and charges per word. Make a key at openrouter.ai/keys, ideally with a spending limit; it is kept in your keychain. \"Check\" confirms the key and lists models. \"Room for each line\": tokens per line, thinking included; too few and a thinking model stops mid-sentence.": "OpenRouter работает в интернете и берёт плату за каждое слово. Создайте ключ на openrouter.ai/keys, лучше с лимитом расходов; он хранится в вашей связке ключей. «Проверить» подтвердит ключ и покажет модели. «Место на реплику» — токенов на реплику вместе с размышлениями; если их мало, думающая модель обрывается на полуслове.",
        "Import…": "Импортировать…",
        "Export…": "Экспортировать…",
        "Copy Agent Prompt": "Скопировать промпт для агента",
        "the prompt is on the clipboard; paste it into any chat model and paste its answer here": "промпт в буфере обмена; вставьте его в любую чат-модель, а её ответ — сюда",
        "Reset Lines": "Сбросить реплики",
        "%d conversations, %d with a flower, %d at night": "разговоров: %d, с цветком: %d, ночью: %d",
        "%@; the creatures stay quiet until this is fixed": "%@; пока это не исправлено, существа молчат",
        "Choose a text file of conversations in the built-in format.": "Выберите текстовый файл с разговорами во встроенном формате.",
        "imported %@": "импортирован файл %@",
        "could not read %@: %@": "не удалось прочитать %@: %@",
        "saved %@": "сохранён файл %@",
        "could not save: %@": "не удалось сохранить: %@",
        "Installed": "Установленные",
        "ready: %@ is installed": "готово: модель %@ установлена",
        "server is up, but %@ is not installed. Pick one under \"Installed\".": "сервер работает, но модель %@ не установлена. Выберите другую в «Установленные».",
        "ready: %@; %@ is available": "готово: %@; модель %@ доступна",
        "%@, but there is no model %@. Search below and click one.": "%@, но модели %@ нет. Найдите другую ниже и щёлкните по ней.",
        "loading models…": "загрузка моделей…",
        "Search models": "Поиск моделей",
        "e.g. flash lite, gemma, free": "например: flash lite, gemma, free",
        "Fetch the list again": "Загрузить список заново",
        "%d more; add a word to narrow it down": "ещё %d; добавьте слово, чтобы сузить поиск",
        "%d models on OpenRouter, cheapest first. Prices are dollars per million tokens.": "Моделей на OpenRouter: %d, сначала дешёвые. Цены — в долларах за миллион токенов.",
        "could not load the list: %@": "не удалось загрузить список: %@",
        "… type more to narrow the list": "… введите больше, чтобы сузить список",

        // Voice
        "casting %@…": "подбираю голос: %@…",
        "Nobody on screen right now.": "Сейчас на экране никого нет.",
        "Casting…": "Подбор…",
        "Cast Everyone with Model": "Подобрать всем моделью",
        "The characters on screen now. Each starts automatic: with \"Voices fit each character's personality\" on, their description and species choose the voice, pitch and speed (old and slow, tiny and quick, a robot, a ghost…); off, voices are only handed out to differ. \"Cast with Model\" asks the brain model instead, which understands any description, and keeps its choice as the character's own; it costs one call. A voice picked here is theirs alone; the automatic ones go round it. Speed and Pitch here multiply the overall sliders on the left; Speed follows pitch can be set for one character alone. \"Auto\" puts a character back to automatic. Settings follow the name, on every engine; an OpenRouter voice the chosen model does not have is ignored. With the Local server, \"Custom blend…\" mixes Kokoro voices, af_bella(2)+am_puck(1) being two parts Bella to one of Puck: endless voices from the 72, free. OpenRouter's Kokoro refuses blends.": "Персонажи, которые сейчас на экране. Сначала у всех автоматический голос: с включённым «Голоса под характер персонажа» описание и вид выбирают голос, высоту и скорость (старый и медленный, крошечный и быстрый, робот, призрак…); если выключено, голоса раздаются просто чтобы различаться. «Подобрать моделью» спрашивает вместо этого модель-мозг, которая понимает любое описание, и закрепляет её выбор за персонажем; это стоит один вызов. Выбранный здесь голос принадлежит только этому персонажу; автоматические его обходят. «Скорость» и «Высота» здесь умножают общие ползунки слева; «Скорость за высотой» можно задать отдельно для персонажа. «Авто» возвращает персонажу автоматический голос. Настройки привязаны к имени, на любом движке; голос OpenRouter, которого нет у выбранной модели, не используется. С локальным сервером «Своя смесь…» смешивает голоса Kokoro: af_bella(2)+am_puck(1) — две части Bella на одну Puck; бесконечно много голосов из 72, бесплатно. Kokoro на OpenRouter смеси не принимает.",
        "cast: %@": "подобрано: %@",
        "Voices joined with +, each with an optional weight: af_bella(2)+am_puck(1) is two parts Bella, one part Puck.": "Голоса через +, у каждого можно указать вес: af_bella(2)+am_puck(1) — две части Bella, одна часть Puck.",
        "Blends %@. Test to hear it.": "Смешивает %@. Нажмите «Прослушать».",
        "Not on the server: %@. Until fixed, this character uses its automatic voice.": "Нет на сервере: %@. Пока это не исправлено, персонаж говорит автоматическим голосом.",
        "Test": "Прослушать",
        "Cast with Model": "Подобрать моделью",
        "Auto": "Авто",
        "Automatic (%@)": "Автоматически (%@)",
        "%@ (not in this model)": "%@ (нет в этой модели)",
        "Custom blend…": "Своя смесь…",
        "Blend": "Смесь",
        "Speed": "Скорость",
        "Pitch": "Высота",
        "Speed follows pitch": "Скорость за высотой",
        "As overall (%@)": "Как в общих (%@)",
        "On: no echo": "Вкл.: без эха",
        "Off: exact pace": "Выкл.: точный темп",
        "Hear them talk out loud": "Слушать их разговоры вслух",
        "Voices": "Голоса",
        "Every character gets a voice of their own": "У каждого персонажа свой голос",
        "Cartoon voices: squeakier, sillier": "Мультяшные голоса: писклявее и смешнее",
        "Voices fit each character's personality": "Голоса под характер персонажа",
        "Speed follows pitch: no echo, higher talks a little faster": "Скорость за высотой: без эха, кто выше — чуть быстрее",
        "Pause before the answer": "Пауза перед ответом",
        "Volume": "Громкость",
        "Stop": "Остановить",
        "System default": "Системный по умолчанию",
        "%@ · %@ · novelty": "%@ · %@ · забавный",
        "The model's first": "Первый голос модели",
        "Keep every line it says": "Сохранять каждую реплику",
        "Kept": "Сохранено",
        "The server's first": "Первый голос сервера",
        "Copy Setup Command": "Скопировать команду установки",
        "copied; paste it into Terminal, wait for \"Uvicorn running\", then Check": "скопировано; вставьте в Терминал, дождитесь «Uvicorn running» и нажмите «Проверить»",
        "Save the built-in lines' voices": "Сохранять озвучку встроенных реплик",
        "Saved": "Сохранено",
        "Clear": "Очистить",
        "ready: %@": "готово: %@",
        "could not load OpenRouter's speech models: %@": "не удалось загрузить речевые модели OpenRouter: %@",
        "The built-in lines (and the Test lines) are saved once said, in the line-voices folder beside the chats, and played from there the next time the same words come in the same voice and speed, so each is made only once: no wait on the server, nothing paid again. Clear forgets them all; each is made again when next said.": "Встроенные реплики (и реплики «Прослушать») сохраняются, как только сказаны, в папку line-voices рядом с разговорами и в следующий раз, когда те же слова звучат тем же голосом и с той же скоростью, играются оттуда — каждая делается лишь однажды: ни ожидания сервера, ни повторной оплаты. «Очистить» забывает их все; каждая будет сделана заново, когда прозвучит снова.",
        "Out loud, each line of a conversation waits for the one before to be said, then follows after the pause set here, its sound fetched while the other was talking; the silent bubble timing is not used. Speed follows pitch: a higher voice also talks a little faster (by the square root of its lift: 1.18× at 1.4×), because a voice asked to talk slowly to make up for the lift smears into an echo. Off keeps the pace exact. Cartoon voices lifts every character's pitch by an amount of its own (1.15 to 1.6 times, on top of Pitch) and picks the playful voices first. Every bubble is read out, in order; when talk runs far ahead of the voice, lines are skipped rather than read late. \"Hear Them Talk\" in the menu turns it on and off.": "Вслух каждая реплика разговора ждёт, пока прозвучит предыдущая, и следует за ней через заданную здесь паузу; её звук загружается, пока говорит другой. Тайминг беззвучных пузырей не используется. «Скорость за высотой»: голос повыше говорит и чуть быстрее (на квадратный корень из подъёма: 1,18× при 1,4×), потому что голос, которого просят говорить медленнее, чтобы скомпенсировать подъём, расплывается в эхо. Выключено — темп точный. «Мультяшные голоса» поднимают высоту каждого персонажа на свою величину (в 1,15–1,6 раза, поверх «Высоты») и сначала выбирают игривые голоса. Каждый пузырь зачитывается по порядку; если разговор сильно обгоняет голос, реплики пропускаются, а не читаются с опозданием. «Слушать их разговоры» в меню включает и выключает голос.",
        "The Mac's own voices: free, offline, instant. More, and better ones, are in System Settings › Accessibility › Spoken Content › System Voice › Manage Voices. With a voice each and Cartoon voices on, they are the Mac's character voices (Grandma, Rocko, Shelley…) and talking novelty ones (Zarvox, Bubbles, Junior…), never the singing ones (Bells, Organ, Superstar…); off, the plain voices, each at a slightly different pitch.": "Собственные голоса Mac: бесплатно, без интернета, мгновенно. Ещё голоса, и получше, — в Системных настройках › Универсальный доступ › Озвучиваемый контент › Системный голос › Управлять голосами. Со своим голосом у каждого и мультяшными голосами это характерные голоса Mac (Grandma, Rocko, Shelley…) и говорящие забавные (Zarvox, Bubbles, Junior…), но не поющие (Bells, Organ, Superstar…); иначе — обычные голоса, каждый чуть другой высоты.",
        "Any speech server on this Mac that answers like OpenAI's /v1/audio/speech and lists voices at /v1/audio/voices, such as Kokoro-FastAPI (port 8880, model \"kokoro\", the same voices as OpenRouter's Kokoro). Free, offline once set up, and nothing is priced. \"Copy Setup Command\" puts Kokoro-FastAPI's install-and-start line on the clipboard; it needs git and uv, and downloads about a gigabyte the first time. LM Studio cannot speak: its server has no speech endpoint.": "Любой речевой сервер на этом Mac, который отвечает как /v1/audio/speech у OpenAI и перечисляет голоса на /v1/audio/voices, например Kokoro-FastAPI (порт 8880, модель «kokoro», те же голоса, что у Kokoro на OpenRouter). Бесплатно, после настройки работает без интернета, ничего не тарифицируется. «Скопировать команду установки» кладёт в буфер обмена строку, которая устанавливает и запускает Kokoro-FastAPI; нужны git и uv, в первый раз скачивается около гигабайта. LM Studio говорить не умеет: у его сервера нет речевого API.",
        "Speech models on OpenRouter sound far more alive, and cost a little per line: Kokoro is about $0.00003 a line. Uses the same key as the brain. What each line cost goes to the spend file a few seconds after it is said. Kept lines are WAV files in the voices folder beside the chats, listed in voices.jsonl with who said what; a line already kept in the same voice and speed is played from there, free. A voice each takes the model's English voices where it says which they are, and with Cartoon voices the playful ones among them (MiniMax's AnimeCharacter or PlayfulGirl, Voxtral's excited and cheerful). The pitch is shifted on this Mac as the clip plays, so it costs nothing extra.": "Речевые модели OpenRouter звучат гораздо живее и стоят немного за реплику: Kokoro — около $0.00003 за реплику. Используется тот же ключ, что и для мозга. Стоимость каждой реплики попадает в файл расходов через несколько секунд после того, как она сказана. Сохранённые реплики — WAV-файлы в папке voices рядом с разговорами, перечисленные в voices.jsonl с тем, кто что сказал; реплика, уже сохранённая тем же голосом и с той же скоростью, играется оттуда бесплатно. Свой голос у каждого берётся из английских голосов модели, если она их помечает, а с мультяшными голосами — из игривых среди них (AnimeCharacter или PlayfulGirl у MiniMax, excited и cheerful у Voxtral). Высота меняется на этом Mac во время проигрывания, так что ничего не стоит.",

        // Costs
        "Cost": "Стоимость",
        "Calls": "Вызовы",
        "Tokens": "Токены",
        "Today": "Сегодня",
        "This month": "В этом месяце",
        "All time": "За всё время",
        "Spent": "Потрачено",
        "Nothing yet.": "Пока ничего.",
        "By feature": "По функциям",
        "Talk is the meetings and pokes (two calls a conversation); paper planes the notes and the catcher's thought; voice every line said by a paid speech model; voice casting each Cast with Model; relationship plots one call per story a pair gets (Bonds tab). Calls from before features were labelled are counted apart.": "Разговоры — это встречи и тычки (два вызова на разговор); бумажные самолётики — записки и мысли поймавшего; голос — каждая реплика, сказанная платной речевой моделью; подбор голоса — каждое «Подобрать моделью»; сюжеты отношений — один вызов на каждую историю пары (вкладка «Отношения»). Вызовы из времён, когда функции ещё не помечались, считаются отдельно.",
        "By model": "По моделям",
        "No calls yet.": "Вызовов пока не было.",
        "Latest calls": "Последние вызовы",
        "The last %d, newest first.": "Последние %d, сначала новые.",
        "The file": "Файл",
        "spend.jsonl, one JSON line per call: time, provider, model, feature, tokens and cost. Plain text on purpose.": "spend.jsonl, по строке JSON на вызов: время, провайдер, модель, функция, токены и стоимость. Простой текст — нарочно.",
        "no price": "без цены",
        "Every call to a model, text or voice, is priced as OpenRouter reports it; LM Studio, a local speech server and the Mac's own voices are free.": "Каждый вызов модели, текстовой или речевой, оценивается так, как сообщает OpenRouter; LM Studio, локальный речевой сервер и собственные голоса Mac бесплатны.",
        "%d calls had no price; a + marks a total that is missing some.": "Вызовов без цены: %d; знак + отмечает сумму, в которой их не хватает.",

        // Chats
        "No chats yet. They talk when they meet on an edge, or pick \"Make Someone Talk\" in the menu.": "Разговоров пока нет. Они разговаривают, когда встречаются на краю, — или заставьте кого-нибудь заговорить из меню.",
        "Nothing on this day.": "В этот день ничего.",
        "Open in Finder": "Открыть в Finder",
        "Open in Terminal": "Открыть в Терминале",
        "%d tok": "%d ток.",
        "Plot: %@": "Сюжет: %@",
        "voice %@ (%@)": "голос %@ (%@)",
        "%d replayed free": "повторено бесплатно: %d",
        "Yesterday": "Вчера",
    ]
}
