extension Strings {
    /// Settings › Sprites, Flowers, Bonds, Calendar, Reminders; the paper note
    /// for a new reminder and the Creature Actions sheet.
    static let ruSettingsB: [String: String] = [
        // Sprites
        "Import Sheet…": "Импортировать лист…",
        "Open Folder": "Открыть папку",
        "Click a creature to put it in the colony or take it out. Creature 1 wears the first one chosen, creature 2 the second, and so on, starting over when they run out. Import a text sheet (.txt) from the kit below, or a 288×96 PNG painted on magenta from the template. Sheets live in %@.":
            "Нажмите на существо, чтобы добавить его в колонию или убрать. Первое существо носит первый выбранный облик, второе — второй и так далее, по кругу. Импортируйте текстовый лист (.txt) из набора ниже или PNG 288×96, нарисованный на пурпурном фоне по шаблону. Листы лежат в %@.",
        "Copy the prompt, paste it into any chat model, replace the placeholder with a description of the creature you want, and save the model's answer as a .txt file. Then Import Sheet…":
            "Скопируйте промпт, вставьте его в любую чат-модель, замените заглушку описанием нужного существа и сохраните ответ модели в файл .txt. Затем — «Импортировать лист…»",
        "Copied": "Скопировано",
        "Copy Prompt": "Скопировать промпт",
        "Save Example Sheet…": "Сохранить пример…",
        "Save PNG Template…": "Сохранить шаблон PNG…",
        "Sprite kit": "Набор для спрайтов",
        "The example sheet is the built-in creature written in the same letters: a good thing to show the model, or to edit by hand. The PNG template marks the cells and the body box for an image model or a paint program; the app cuts the magenta away on import.":
            "Пример — встроенное существо, записанное теми же буквами: его полезно показать модели или поправить вручную. Шаблон PNG размечает клетки и рамку тела для модели-художника или графического редактора; пурпурный фон приложение вырезает при импорте.",
        "Delete this imported creature": "Удалить это импортированное существо",
        "A sprite text file from the kit, or a 288×96 PNG on magenta.": "Текстовый файл спрайта из набора или PNG 288×96 на пурпурном фоне.",

        // Flowers
        "Flower lasts": "Цветок живёт",
        "The one with the flower follows the giver while it lasts": "Получивший цветок ходит за дарителем, пока цветок жив",
        "Wearing": "Цветок на голове",
        "Every third meeting of a pair, one gives the other a flower, worn on the head until it wilts or is planted. With the box ticked, the wearer trails the giver around the edge meanwhile. A creature wearing a flower walks past everyone without bumping.":
            "На каждой третьей встрече пары один дарит другому цветок, и тот носит его на голове, пока цветок не завянет или не будет посажен. С галочкой получивший тем временем ходит по краю за дарителем. Существо с цветком проходит мимо всех, ни с кем не сталкиваясь.",
        "They plant their flowers where they like": "Сажают цветы, где им нравится",
        "A planted flower lasts": "Посаженный цветок живёт",
        "Flowers in the ground at most": "Цветов в земле не больше",
        "Clear Planted Flowers": "Убрать посаженные цветы",
        "Nothing was planted.": "Ничего не посажено.",
        "flower pulled up.|flowers pulled up.": "цветок выдернут.|цветка выдернуто.|цветков выдернуто.",
        "Planting": "Посадка",
        "After wearing it a while, each one stops following its giver, goes looking for the kind of spot its character likes and plants the flower in the edge there. What it likes comes from who it is: Blocky wants the bottom edge, Pip the ceiling, Ruth a neat row beside the others, Dot plants at once, Zed waits for dark. If nowhere suits before the flower would wilt, it plants it where it stands. Planting one more than the most wilts the oldest. Clear Planted Flowers, here or in the menu, pulls them all up at once. Planted flowers are not kept when the app quits.":
            "Поносив цветок, каждый перестаёт ходить за дарителем, ищет место по своему характеру и сажает цветок там, у края. Что кому нравится, зависит от того, кто он: Blocky хочет нижний край, Pip — потолок, Ruth — ровный ряд рядом с другими, Dot сажает сразу, Zed ждёт темноты. Если до увядания подходящего места не нашлось, цветок сажается там, где стоит его хозяин. Лишний сверх предела цветок заставляет завянуть самый старый. «Убрать посаженные цветы», здесь или в меню, выдёргивает их все разом. После выхода из приложения посаженные цветы не сохраняются.",
        "Who plants where": "Кто где сажает",
        "Read from each character's description and its species on the Talk tab, the same way voices are cast: words like bottom, ceiling, corner, quiet, cheerful, counts, sleepy or fast. Edit a description and this changes with it.":
            "Берётся из описания каждого персонажа и его вида на вкладке «Разговоры», так же как подбираются голоса: по словам вроде bottom, ceiling, corner, quiet, cheerful, counts, sleepy или fast. Измените описание — изменится и это.",

        // Bonds
        "Pairs who live together get a story": "У пар, живущих вместе, появляется история",
        "First story after": "Первая история через",
        " h": " ч",
        "Reset Prompt": "Сбросить промпт",
        "Forget": "Забыть",
        "A story lasts": "История длится",
        "conversation|conversations": "разговор|разговора|разговоров",
        "Stories": "Истории",
        "The prompt that writes a story": "Промпт, который пишет историю",
        "Placeholders: %@. The answer needs a PLOT: line, and may have a BOND: line. {relationship} in the Talk prompt places the story; without it, it goes at the end.":
            "Подстановки: %@. В ответе нужна строка PLOT:, может быть и строка BOND:. {relationship} в промпте разговора задаёт место истории; без него она идёт в конец.",
        "Nobody has shared the screen yet.": "Пока никто не делил экран.",
        "Who lives with whom": "Кто с кем живёт",
        "Time counts while both are on screen, and is kept by name: rename a character and it starts again as a stranger.":
            "Время идёт, пока оба на экране, и хранится по имени: переименуйте персонажа — и он начнёт заново как незнакомец.",
        "Forget All": "Забыть всех",
        "Once two characters have shared the screen this long, the model writes them a small story and a line on how they get on. A few dozen words of it go into their prompts; when it has run its course, the next grows from the last. One short call per story (Costs › Relationship plots).":
            "Когда двое персонажей пробыли на экране вместе столько времени, модель пишет им маленькую историю и строчку о том, как они ладят. Несколько десятков слов из неё попадают в их промпты; когда история исчерпана, следующая вырастает из прошлой. Один короткий вызов на историю (Расходы › Сюжеты отношений).",
        "Time together is still counted meanwhile: once a model is chosen, a pair that has lived together long enough gets its first story at its next talk.":
            "Время вместе всё равно считается: когда модель будет выбрана, пара, прожившая вместе достаточно, получит первую историю при следующем разговоре.",
        "Part %d of %d: %@": "Часть %d из %d: %@",
        "Last story: %@": "Прошлая история: %@",
        "together %@": "вместе %@",
        "talk|talks": "беседа|беседы|бесед",
        "story|stories": "история|истории|историй",

        // Calendar
        "They know the time of day": "Знают время суток",
        "They know the day of the week and the date": "Знают день недели и дату",
        "The day": "День",
        "Your Mac's clock and calendar, told to the model before every line and paper plane: \"late evening (22:40)\", \"Saturday, 26 September 2026\". This is apart from the colony's own day and night, which only says when they sleep.":
            "Часы и календарь вашего Mac сообщаются модели перед каждой репликой и бумажным самолётиком: «поздний вечер (22:40)», «суббота, 26 сентября 2026». Это не связано с днём и ночью колонии, которые решают только, когда им спать.",
        "Jewish holidays": "Еврейские праздники",
        "Christian holidays": "Христианские праздники",
        "Muslim holidays": "Мусульманские праздники",
        "Mention a holiday": "Упоминать праздник",
        "only on the day": "только в сам день",
        "day ahead|days ahead": "за %d день|за %d дня|за %d дней",
        "Holidays": "Праздники",
        "On a holiday they know it, and which day of it (\"day 3 of Sukkot\"); before one, how far off it is. Jewish dates come from the Hebrew calendar and Muslim ones from the Islamic (Umm al-Qura) calendar, both built into macOS, so nothing is looked up online; a holiday that starts at sundown \"begins this evening\" the evening before. Where the new moon is sighted locally, a Muslim date can fall a day apart. With the built-in lines, one conversation in three on a holiday is about it; they only know a holiday on the day, so how far ahead to mention one needs a model.":
            "В праздник они знают о нём и какой это его день («3-й день Суккота»); до праздника — сколько до него осталось. Еврейские даты берутся из еврейского календаря, мусульманские — из исламского (Умм аль-Кура); оба встроены в macOS, так что ничего не ищется в сети. Праздник, начинающийся на закате, «начинается сегодня вечером» накануне. Там, где молодую луну наблюдают на месте, мусульманская дата может отличаться на день. Со встроенными репликами в праздник каждый третий разговор — о нём; но они знают о празднике только в сам день, поэтому упоминать его заранее можно лишь с моделью.",
        "Nothing: every box is off.": "Ничего: все галочки сняты.",
        "What they know right now": "Что они знают сейчас",
        "This goes into {situation} in the Talk prompts, and at the top of a paper plane's note.":
            "Это попадает в {situation} в промптах разговора и в начало записки бумажного самолётика.",
        "What a model would be told. The built-in lines use only today's holiday, when there is one.":
            "Что узнала бы модель. Встроенные реплики знают только о сегодняшнем празднике, если он есть.",
        "No holidays ticked.": "Праздники не выбраны.",
        "Nothing in the next 60 days.": "В ближайшие 60 дней ничего.",
        "Coming up in the next 60 days": "Ближайшие 60 дней",
        "tomorrow": "завтра",
        "in %@": "через %@",
        "day|days": "день|дня|дней",

        // Reminders
        "Remind me to": "Напомнить",
        "Stretch, call mom, stand-up…": "Размяться, позвонить маме, созвон…",
        "When": "Когда",
        "Repeat": "Повтор",
        "In 5 min": "Через 5 мин",
        "In 30 min": "Через 30 мин",
        "In 1 hour": "Через час",
        "Add Reminder": "Добавить напоминание",
        "New reminder": "Новое напоминание",
        "When the time comes, one of the creatures folds it into a paper plane and throws it at you. A time already past is delivered straight away. Repeating reminders keep their time of day; weekdays skip Saturday and Sunday.":
            "Когда придёт время, одно из существ сложит напоминание в бумажный самолётик и бросит в вас. Уже прошедшее время доставляется сразу. Повторяющиеся напоминания сохраняют время суток; «по будням» пропускает субботу и воскресенье.",
        "Reminders arrive by paper plane": "Напоминания прилетают самолётиком",
        "Letter stays open": "Письмо открыто",
        "The thrower reads its note out loud": "Бросивший читает записку вслух",
        "Add a Reminder… opens a paper note": "«Добавить напоминание…» открывает бумажную записку",
        "Send a Test Letter": "Отправить тестовое письмо",
        "This is what a reminder looks like": "Вот так выглядит напоминание",
        "Delivery": "Доставка",
        "No reminders yet.": "Напоминаний пока нет.",
        "Your reminders": "Ваши напоминания",
        "Sent one-off reminders stay here, greyed, until you clear them.": "Отправленные разовые напоминания остаются здесь серыми, пока вы их не очистите.",
        "Clear Sent": "Очистить отправленные",
        "The plane flies to the middle of the screen your cursor is on, comes at you and opens into a letter: your reminder, a note from whoever threw it, and their signature. Click the letter to fold it away; otherwise it folds itself after this long, counting only while you are at the computer. Off: nothing is delivered, and what came due meanwhile arrives when you turn it back on.":
            "Самолётик летит в середину экрана, где курсор, подлетает к вам и раскрывается в письмо: ваше напоминание, записка от бросившего и его подпись. Нажмите на письмо, чтобы сложить его; иначе оно сложится само через это время, считая только пока вы за компьютером. Выключено: ничего не доставляется, а всё, чей срок подошёл, прилетит, когда вы включите снова.",
        "With a model, the note is written for the moment (Costs › Reminders).": "С моделью записка пишется к моменту (Расходы › Напоминания).",
        "A paper note: ⌘R in the menu opens a sheet of the same paper to write a reminder on; off, ⌘R opens this tab.":
            "Бумажная записка: ⌘R в меню открывает лист той же бумаги, чтобы написать напоминание; если выключено, ⌘R открывает эту вкладку.",
        "Sent %@": "Отправлено %@",
        "Send Now": "Отправить сейчас",
        "Delete": "Удалить",

        // The paper note
        "A NOTE FOR THE LEDGELINGS · %@ IS READING OVER THE EDGE": "ЗАПИСКА ДЛЯ LEDGELINGS · %@ ЗАГЛЯДЫВАЕТ ЧЕРЕЗ КРАЙ",
        "A NOTE FOR THE LEDGELINGS": "ЗАПИСКА ДЛЯ LEDGELINGS",
        "REMIND ME TO": "НАПОМНИ МНЕ",
        "stretch, call mom, stand-up…": "размяться, позвонить маме, созвон…",
        "WHEN": "КОГДА",
        "past: it comes\nstraight away": "уже прошло:\nпридёт сразу",
        "IN 5 MIN": "ЧЕРЕЗ 5 МИН",
        "IN 30 MIN": "ЧЕРЕЗ 30 МИН",
        "IN 1 HOUR": "ЧЕРЕЗ ЧАС",
        "TOMORROW 9:00": "ЗАВТРА 9:00",
        "REPEAT": "ПОВТОР",
        "write something first": "сначала напишите что-нибудь",
        "NEVER MIND": "ОТМЕНА",
        "FOLD IT INTO A PLANE": "СЛОЖИТЬ САМОЛЁТИК",

        // Creature Actions
        "Everyone jumps.": "Все подпрыгивают.",
        "Someone has something to say.": "Кому-то есть что сказать.",
        "Nobody talks: %@.": "Никто не говорит: %@.",
        "Two of them sit down to tea.": "Двое садятся пить чай.",
        "No tea: %@.": "Чая не будет: %@.",
        "A paper plane goes up.": "Бумажный самолётик взлетает.",
        "No plane: %@.": "Самолётика не будет: %@.",
        "They come back out.": "Они выходят обратно.",
        "Good morning.": "Доброе утро.",
        "Good night.": "Спокойной ночи.",
        "Pulled up the flower.": "Цветок выдернут.",
        "Pulled up %@.": "Выдернуто: %@.",
        "flower|flowers": "цветок|цветка|цветков",
        "They run home.": "Они бегут домой.",
        "MAKE THEM JUMP": "ПУСТЬ ПОДПРЫГНУТ",
        "MAKE SOMEONE TALK": "ПУСТЬ КТО-ТО ЗАГОВОРИТ",
        "TEA PARTY ON": "ИДЁТ ЧАЕПИТИЕ",
        "HAVE A TEA PARTY": "УСТРОИТЬ ЧАЕПИТИЕ",
        "SEND A PAPER PLANE": "ЗАПУСТИТЬ САМОЛЁТИК",
        "ADD A REMINDER": "ДОБАВИТЬ НАПОМИНАНИЕ",
        "BRING THEM BACK": "ВЕРНУТЬ ИХ",
        "HIDE THEM FOR A WHILE": "СПРЯТАТЬ НА ВРЕМЯ",
        "WAKE THEM UP": "РАЗБУДИТЬ",
        "PUT THEM TO SLEEP": "УЛОЖИТЬ СПАТЬ",
        "CLEAR THE FLOWER": "УБРАТЬ ЦВЕТОК",
        "CLEAR FLOWERS": "УБРАТЬ ЦВЕТЫ",
        "CLEAR %d FLOWER|CLEAR %d FLOWERS": "УБРАТЬ %d ЦВЕТОК|УБРАТЬ %d ЦВЕТКА|УБРАТЬ %d ЦВЕТКОВ",
        "they are hiding": "они прячутся",
        "off in settings": "выкл. в настройках",
        "one at a time": "по одному",
        "one is in the air": "один уже летит",
        "%@ left": "ещё %@",
        "night is set to 0": "ночь выключена",
        "dawn in %@": "до рассвета %@",
        "dusk in %@": "до заката %@",
        "none planted": "ничего не посажено",
        "5 MIN": "5 МИН",
        "15 MIN": "15 МИН",
        "30 MIN": "30 МИН",
        "1 H": "1 Ч",
        "2 H": "2 Ч",
        "4 H": "4 Ч",
        "TILL 8:00": "ДО 8:00",
        "WHAT SHOULD THEY DO? · %@ IS WAITING": "ЧТО ИМ СДЕЛАТЬ? · %@ ЖДЁТ",
        "WHAT SHOULD THEY DO?": "ЧТО ИМ СДЕЛАТЬ?",
        "HIDE FOR": "СПРЯТАТЬ НА",
        "click a picture, or press its letter": "нажмите на картинку или её букву",
        "DONE": "ГОТОВО",
    ]
}
