namespace Ledgelings.Core;

public static partial class WindowsStrings
{
    /// <summary>The settings window, the colour dialog and the paper sheets: what only Windows says.</summary>
    private static readonly Dictionary<string, string> RuSettings = new()
    {
        ["Blue"] = "Синий",
        ["Cancel"] = "Отмена",
        ["Colour"] = "Цвет",
        ["Green"] = "Зелёный",
        ["Hex"] = "Код",
        ["OK"] = "ОК",
        ["Red"] = "Красный",
        ["Add a Reminder"] = "Добавить напоминание",
        ["Every call to a model, text or voice, is priced as OpenRouter reports it; LM Studio, a local speech server and Windows' own voices are free."] = "Каждый вызов модели, текстовой или речевой, оценивается так, как сообщает OpenRouter; LM Studio, локальный речевой сервер и собственные голоса Windows бесплатны.",
        ["A paper note: Add a Reminder… (%@ anywhere, or the tray menu) opens a sheet of the same paper to write a reminder on; off, it opens this tab."] = "Бумажная записка: «Добавить напоминание…» (%@ где угодно или меню в трее) открывает лист той же бумаги, чтобы написать напоминание; если выключено, открывается эта вкладка.",
        ["Text"] = "Текст",
        ["All files"] = "Все файлы",
        ["the clipboard is busy; try again"] = "буфер обмена занят; попробуйте ещё раз",
        ["Sprite sheets"] = "Листы спрайтов",
        ["OpenRouter runs on the internet and charges per word. Make a key at openrouter.ai/keys, ideally with a spending limit; it is kept in the Windows Credential Manager. \"Check\" confirms the key and lists models. \"Room for each line\": tokens per line, thinking included; too few and a thinking model stops mid-sentence."] = "OpenRouter работает в интернете и берёт плату за каждое слово. Создайте ключ на openrouter.ai/keys, лучше с лимитом расходов; он хранится в диспетчере учётных данных Windows. «Проверить» подтвердит ключ и покажет модели. «Место на реплику» — токенов на реплику вместе с размышлениями; если их мало, думающая модель обрывается на полуслове.",
        ["Any speech server on this PC that answers like OpenAI's /v1/audio/speech and lists voices at /v1/audio/voices, such as Kokoro-FastAPI (port 8880, model \"kokoro\", the same voices as OpenRouter's Kokoro). Free, offline once set up, and nothing is priced. \"Copy Setup Command\" puts Kokoro-FastAPI's install-and-start line on the clipboard, for PowerShell; it needs git and uv, and downloads about a gigabyte the first time. LM Studio cannot speak: its server has no speech endpoint."] = "Любой речевой сервер на этом ПК, который отвечает как /v1/audio/speech у OpenAI и перечисляет голоса на /v1/audio/voices, например Kokoro-FastAPI (порт 8880, модель «kokoro», те же голоса, что у Kokoro на OpenRouter). Бесплатно, после настройки работает без интернета, ничего не тарифицируется. «Скопировать команду установки» кладёт в буфер обмена строку для PowerShell, которая устанавливает и запускает Kokoro-FastAPI; нужны git и uv, в первый раз скачивается около гигабайта. LM Studio говорить не умеет: у его сервера нет речевого API.",
        ["copied; paste it into PowerShell, wait for \"Uvicorn running\", then Check"] = "скопировано; вставьте в PowerShell, дождитесь «Uvicorn running» и нажмите «Проверить»",
        ["Speech models on OpenRouter sound far more alive, and cost a little per line: Kokoro is about $0.00003 a line. Uses the same key as the brain. What each line cost goes to the spend file a few seconds after it is said. Kept lines are WAV files in the voices folder beside the chats, listed in voices.jsonl with who said what; a line already kept in the same voice and speed is played from there, free. A voice each takes the model's English voices where it says which they are, and with Cartoon voices the playful ones among them (MiniMax's AnimeCharacter or PlayfulGirl, Voxtral's excited and cheerful). The pitch is shifted on this PC as the clip plays, so it costs nothing extra."] = "Речевые модели OpenRouter звучат гораздо живее и стоят немного за реплику: Kokoro — около $0.00003 за реплику. Используется тот же ключ, что и для мозга. Стоимость каждой реплики попадает в файл расходов через несколько секунд после того, как она сказана. Сохранённые реплики — WAV-файлы в папке voices рядом с разговорами, перечисленные в voices.jsonl с тем, кто что сказал; реплика, уже сохранённая тем же голосом и с той же скоростью, играется оттуда бесплатно. Свой голос у каждого берётся из английских голосов модели, если она их помечает, а с мультяшными голосами — из игривых среди них (AnimeCharacter или PlayfulGirl у MiniMax, excited и cheerful у Voxtral). Высота меняется на этом ПК во время проигрывания, так что ничего не стоит.",
        ["Windows' own voices: free, offline, instant. More are added in Windows Settings › Time & language › Speech; the ones Windows offers to desktop programs are listed here. Windows has no character or novelty voices, so Cartoon voices lifts the pitch instead; with a voice each, the voices go round the cast, each at a slightly different pitch."] = "Собственные голоса Windows: бесплатно, без интернета, мгновенно. Новые добавляются в Параметрах Windows › Время и язык › Речь; здесь перечислены те, что Windows даёт обычным программам. Характерных и забавных голосов в Windows нет, поэтому мультяшные голоса просто поднимают высоту; со своим голосом у каждого голоса раздаются по кругу, каждый чуть другой высоты.",
        ["Creature 1 wears the first colour, creature 2 the second, and so on, starting over when the colours run out. Click a swatch to change it."] = "Существо 1 носит первый цвет, существо 2 — второй и так далее; когда цвета кончаются, всё начинается сначала. Щёлкните по образцу, чтобы его изменить.",
        ["Every creature gets its own size between the two. Set them equal and they all match. On a high-dpi monitor the sizes scale with it, so 3× is the same size as on a Mac."] = "Каждое существо получает свой размер между этими двумя. Сделайте их равными — и все будут одного размера. На мониторе с высоким dpi размеры масштабируются вместе с ним, так что 3× такого же размера, как на Mac.",
        ["Installed models"] = "Установленные модели",
        ["Menus, settings and what the creatures say. Prompts you edited stay as written. Login uses the per-user Startup list; Task Manager › Startup apps shows it too."] = "Меню, настройки и речь существ. Изменённые вами промпты не меняются. Запуск — через список автозагрузки пользователя; его показывает и «Диспетчер задач › Автозагрузка приложений».",
        ["On a holiday they know it, and which day of it (\"day 3 of Sukkot\"); before one, how far off it is. Jewish dates come from the Hebrew calendar and Muslim ones from the Islamic (Umm al-Qura) calendar, both built into Windows, so nothing is looked up online; a holiday that starts at sundown \"begins this evening\" the evening before. Where the new moon is sighted locally, a Muslim date can fall a day apart. With the built-in lines, one conversation in three on a holiday is about it; they only know a holiday on the day, so how far ahead to mention one needs a model."] = "В праздник они знают о нём и какой это его день («3-й день Суккота»); до праздника — сколько до него осталось. Еврейские даты берутся из еврейского календаря, мусульманские — из исламского (Умм аль-Кура); оба встроены в Windows, так что ничего не ищется в сети. Праздник, начинающийся на закате, «начинается сегодня вечером» накануне. Там, где молодую луну наблюдают на месте, мусульманская дата может отличаться на день. Со встроенными репликами в праздник каждый третий разговор — о нём; но они знают о празднике только в сам день, поэтому упоминать его заранее можно лишь с моделью.",
        ["Open in Explorer"] = "Открыть в Проводнике",
        ["Remove this character"] = "Убрать этого персонажа",
        ["Show in Explorer"] = "Показать в Проводнике",
        ["Chased or picked up this often in that time, a creature jumps on the cursor and rides along on it, telling you off now and then in its own words and the cursor mood, until you shake it off or the limit runs out. Holding the pointer still, you cannot move it until it lets go, after 10 s at the latest. Escape lets go too, whichever app is in front. No permission is needed."] =
            "Если существо столько раз за это время гоняли или хватали, оно прыгает на курсор и катается на нём, то и дело высказывая вам всё в настроении курсора, пока вы его не стряхнёте или не выйдет предел. Держа указатель на месте, оно не даёт его двигать, но не дольше 10 с. Escape тоже отпускает, какое бы приложение ни было впереди. Разрешения не нужны.",
        ["The characters on screen now. Each starts automatic: with \"Voices fit each character's personality\" on, their description and species choose the voice, pitch and speed (old and slow, tiny and quick, a robot, a ghost…); off, voices are only handed out to differ. \"Cast with Model\" asks the brain model instead, which understands any description, and keeps its choice as the character's own; it costs one call. A voice picked here is theirs alone; the automatic ones go round it. Speed and Pitch here multiply the overall sliders above; Speed follows pitch can be set for one character alone. \"Auto\" puts a character back to automatic. Settings follow the name, on every engine; an OpenRouter voice the chosen model does not have is ignored. With the Local server, \"Custom blend…\" mixes Kokoro voices, af_bella(2)+am_puck(1) being two parts Bella to one of Puck: endless voices from the 72, free. OpenRouter's Kokoro refuses blends."] = "Персонажи, которые сейчас на экране. Сначала у всех автоматический голос: с включённым «Голоса под характер персонажа» описание и вид выбирают голос, высоту и скорость (старый и медленный, крошечный и быстрый, робот, призрак…); если выключено, голоса раздаются просто чтобы различаться. «Подобрать моделью» спрашивает вместо этого модель-мозг, которая понимает любое описание, и закрепляет её выбор за персонажем; это стоит один вызов. Выбранный здесь голос принадлежит только этому персонажу; автоматические его обходят. «Скорость» и «Высота» здесь умножают общие ползунки выше; «Скорость за высотой» можно задать отдельно для персонажа. «Авто» возвращает персонажу автоматический голос. Настройки привязаны к имени, на любом движке; голос OpenRouter, которого нет у выбранной модели, не используется. С локальным сервером «Своя смесь…» смешивает голоса Kokoro: af_bella(2)+am_puck(1) — две части Bella на одну Puck; бесконечно много голосов из 72, бесплатно. Kokoro на OpenRouter смеси не принимает.",
        ["Time, 24-hour: 14:30"] = "Время, 24-часовой формат: 14:30",
        ["Your PC's clock and calendar, told to the model before every line and paper plane: \"late evening (22:40)\", \"Saturday, 26 September 2026\". This is apart from the colony's own day and night, which only says when they sleep."] = "Часы и календарь вашего ПК сообщаются модели перед каждой репликой и бумажным самолётиком: «поздний вечер (22:40)», «суббота, 26 сентября 2026». Это не связано с днём и ночью колонии, которые решают только, когда им спать.",
    };
}
