<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Version>0.17.0</Version>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Authors>Evgeny Alterman</Authors>
    <Product>Ledgelings</Product>
  </PropertyGroup>
</Project>
